DELETE FROM PRET;
DELETE FROM LECTEUR;
DELETE FROM LIVRE;

INSERT INTO LECTEUR VALUES(1,'Roman Policier','10 rue des fleurs');
INSERT INTO LECTEUR VALUES(2,'Patrick Chesne','12 avenue Clang');
INSERT INTO LECTEUR VALUES(3,'Caroline Dusquesne','patio Robert');
INSERT INTO LECTEUR VALUES(4,'Gaspard Dupont','porte droite');
INSERT INTO LECTEUR VALUES(5,'Rom�o Trichet','?');
INSERT INTO LECTEUR VALUES(6,'Sophie Duchamp','?');
INSERT INTO LECTEUR VALUES(7,'Mohammed Khaled','10 place Desfetes');
INSERT INTO LECTEUR VALUES(8,'Ernest Njike','1 rue delime');
INSERT INTO LECTEUR VALUES(9,'Robert Laffontaine','15 rue du commandant Gouttedeau');
INSERT INTO LECTEUR VALUES(10,'Elsa Caramel','place des grands troncs');
INSERT INTO LECTEUR VALUES(11,'Maurice Leplanqu�','rue du trou');
INSERT INTO LECTEUR VALUES(12,'Dominique Calende','Quelquepart');
INSERT INTO LECTEUR VALUES(13,'Lali T�raire','impasse de la lettre');
INSERT INTO LECTEUR VALUES(14,'Lascard Pomme','jardin du coin');

INSERT INTO LIVRE VALUES ('TEND01','La qu�te de l''oiseau du temps','BD','R�gis Loisel et Serge Le Tendre');
INSERT INTO LIVRE VALUES ('MARI01','Scorpion','BD','Stephen Desberg et  Enrico Marini');
INSERT INTO LIVRE VALUES ('SATR01','Pers�polis','BD','Marjane Satrapi');
INSERT INTO LIVRE VALUES ('MALF01','Golden City','BD','Daniel Pecqueur et Nicolas Malfin');
INSERT INTO LIVRE VALUES ('GOSC01','Ast�rix et le rentr�e gauloise','BD','Albert Uderzo et Ren� Goscinny');
INSERT INTO LIVRE VALUES ('GIRA01','OK Corral','BD','Charlier et Giraud');
INSERT INTO LIVRE VALUES ('LAPI01','Agadamgorodok','BD','Pierre Bailly et Denis Lapi�re');
INSERT INTO LIVRE VALUES ('GIME01','La caste des M�ta-Barons','BD','Alexandro Jodorowsky et Juan Gimenez');
INSERT INTO LIVRE VALUES ('MARG01','Lulu s''maque','BD','Frank Margerin');
INSERT INTO LIVRE VALUES ('PRAT01','Fable � Venise','BD','Hugo Pratt');
INSERT INTO LIVRE VALUES ('HAUS01','Les chasseurs de l''aube','BD','Ren� Hausman');
INSERT INTO LIVRE VALUES ('GREG01','Olivier Rameau','BD','Dany et Greg');
INSERT INTO LIVRE VALUES ('GUAR01','Blacksad','BD','Guarnido');
INSERT INTO LIVRE VALUES ('SFAR02','Les Poup�es de Jerusalem (Professeur Bell T. 2 )','BD','Joann Sfar');
INSERT INTO LIVRE VALUES ('SATR04','Persepolis','BD','Marjan Satrapi');
INSERT INTO LIVRE VALUES ('GILB01','Chiffon','BD','David Gilbert');
INSERT INTO LIVRE VALUES ('THOM01','Adieu, Chunky Rice','BD','Craig Thompson');
INSERT INTO LIVRE VALUES ('VAUT01','L''espoir assassin� (Le Cri du Peuple, n°2)','BD','Tardi et Vautrin');
INSERT INTO LIVRE VALUES ('GIBR01','Le Vol du Corbeau','BD','Gibrat');
INSERT INTO LIVRE VALUES ('FROI01','Chroniques de la lune noire - L''Aigle Foudroy�','BD','Pontet - Froideval');
INSERT INTO LIVRE VALUES ('CLOW01','David Boring','BD','Daniel Clowes');
INSERT INTO LIVRE VALUES ('MOUR01','Trolls dans la brume','BD','S. Arleston, J.L. Mourier');
INSERT INTO LIVRE VALUES ('GIBR02','Le Vol du Corbeau','BD','Gibrat');
INSERT INTO LIVRE VALUES ('BARJ01','La nuit des temps','BD','Ren� Barjavel');
INSERT INTO LIVRE VALUES ('HADD01','Le jour o� Lacan m''a adopt�','Essai','G�rard Haddad');
INSERT INTO LIVRE VALUES ('GUEN01','Paroles d''�toiles','Essai','Sous la direction de JP Gu�no');
INSERT INTO LIVRE VALUES ('DAVI01','L''esprit de Dieu','Essai','Paul Davies');
INSERT INTO LIVRE VALUES ('MURR01','Jimi Hendrix','Essai','Charles Shaar Murray');
INSERT INTO LIVRE VALUES ('MASP01','Les abeilles et la gu�pe','Essai','Fran�ois Maspero');
INSERT INTO LIVRE VALUES ('TSHI01','L''Internet, son Web et son E-mail en Afrique. Approche critique','Essai','Raphaël NTAMBUE-TSHIMBULU');
INSERT INTO LIVRE VALUES ('WERB01','Encyclop�die du savoir relatif et absolu','Essai','Bernard Werber');
INSERT INTO LIVRE VALUES ('PRES01','Elvis mon amour','Essai','Priscilla Presley');
INSERT INTO LIVRE VALUES ('GROD01','Le livre du �a','Essai','Georg Groddeck');
INSERT INTO LIVRE VALUES ('KANA01','Ma guerre � l''indiff�rence','Essai','Jean-S�lim Kanaan');
INSERT INTO LIVRE VALUES ('KERT01','Un Autre - Chronique d''une m�tamorphose','Essai','Imre Kert�sz');
INSERT INTO LIVRE VALUES ('BARN01','Something to declare','Essai','Julian Barnes');
INSERT INTO LIVRE VALUES ('REVE01','L''obsession anti-am�ricaine','Essai','Jean-Francois Revel');
INSERT INTO LIVRE VALUES ('LABA01','L''Europe f�d�rale','Essai','Bernard Guetta - Philippe Labarde');
INSERT INTO LIVRE VALUES ('CHOM01','De la propagande','Essai','Noam Chomsky');
INSERT INTO LIVRE VALUES ('ROJZ01','Comment ne pas devenir �lecteur du Front National','Essai','V�ronoque Le Gouaziou et Charles Rojzman');
INSERT INTO LIVRE VALUES ('JARD01','1+1+1=une r�volution','Essai','Alexandre Jardin');
INSERT INTO LIVRE VALUES ('MARX01','Correspondance de Groucho Marx','Essai','Groucho Marx');
INSERT INTO LIVRE VALUES ('GUIS01','Th�se et foutaises sur les attentats du 11 septembre','Essai','Guillaume Dasqui�, Jean Guisnel');
INSERT INTO LIVRE VALUES ('COLI01','Voil� : dans les coulisses de Voici','Essai','Jacques Colin');
INSERT INTO LIVRE VALUES ('BOUQ01','Zacarias Moussaoui, mon fr�re','Essai','A.S. Moussaoui, F. Bouquillat');
INSERT INTO LIVRE VALUES ('AULN01','La dame des 35 heures','Essai','Philippe Alexandre et B�atrix de l''Aulnoit');
INSERT INTO LIVRE VALUES ('BEAU01','Le tir � la cible, de l''initiation � la comp�tition','Essai','Jacques Beausergent');
INSERT INTO LIVRE VALUES ('ROEY01','Cybersexe','Essai','Luc Calis, Salvino A. Salvaggio, Sylvie Van Roey');
INSERT INTO LIVRE VALUES ('CROI01','Ecolos, petites esbroufes et gros mensonges','Essai','Jean Paul Croiz');
INSERT INTO LIVRE VALUES ('WINN01','Hommage','Essai','Maurice Winnykamen');
INSERT INTO LIVRE VALUES ('MONO01','Et si l''aventure humaine devait  �chouer','Essai','Th�odore MONOD');
INSERT INTO LIVRE VALUES ('THIE01','A bout de course','Essai','Thierry');
INSERT INTO LIVRE VALUES ('FRAN01','Le Journal d''Anne Frank','Essai','Anne Frank');
INSERT INTO LIVRE VALUES ('LAGI01','Les mille yeux de Brian de Palma','Essai','Luc Lagier');
INSERT INTO LIVRE VALUES ('LACO01','Enron, la faillite qui �branla l''Am�rique','Essai','Anne-Sylvaine Chassany et Jean-Philippe Lacour');
INSERT INTO LIVRE VALUES ('SART01','L''existentialisme est un humanisme','Essai','Jean-Paul Sartre');
INSERT INTO LIVRE VALUES ('PAUL01','Vos yeux Madame','Essai','Ivanka Paul');
INSERT INTO LIVRE VALUES ('MERN01','Le harem politique','Essai','Fatima Mernissi');
INSERT INTO LIVRE VALUES ('ONFR01','Arch�ologie du pr�sent','Essai','Michel Onfray');
INSERT INTO LIVRE VALUES ('ECO01','Apostille Au nom de la rose','Essai','Umberto Eco');
INSERT INTO LIVRE VALUES ('MEBA01','Les enfants lumi�res','Essai','Agn�s Wachter-M�barki');
INSERT INTO LIVRE VALUES ('FLEU01','Sans p�re ni rep�res','Essai','Catherine Lehoux-Fleury');
INSERT INTO LIVRE VALUES ('MOOR02','Mike contre-attaque !','Essai','Michael Moore');
INSERT INTO LIVRE VALUES ('SACK01','L''homme qui prenait sa femme pour un chapeau ','Essai','Olivier Sacks');
INSERT INTO LIVRE VALUES ('TRIN01','Ma fille, Marie','Essai','Nadine Trintignant');
INSERT INTO LIVRE VALUES ('COLL01','Si le monde �tait un village de 100 personnes','Essai','Collectif');
INSERT INTO LIVRE VALUES ('PAVL01','Matin brun','Essai','Franck Pavloff');
INSERT INTO LIVRE VALUES ('OVID01','L''art d''aimer','Essai','Ovide');
INSERT INTO LIVRE VALUES ('SOUA02','Br�l�e vive','Essai','Souad');
INSERT INTO LIVRE VALUES ('DE01','La vie � en mourir : Lettres de fusill�s 1941-1944','Essai','Guy Krivopissko (sous la direction de');
INSERT INTO LIVRE VALUES ('SOUA03','Br�l�e vive','Essai','Souad');
INSERT INTO LIVRE VALUES ('CART01','Bien entendu... c''est off','Essai','Daniel Carton');
INSERT INTO LIVRE VALUES ('LEVY02','Qui a tu� Daniel Pearl ?','Essai','Bernard-Henry L�vy');
INSERT INTO LIVRE VALUES ('ZEPE01','Les sales coups de la CIA','Essai','Mark Zepezauer');
INSERT INTO LIVRE VALUES ('KAUF01','Corps de femmes, regards d''hommes','Essai','Jean-Claude Kaufmann');
INSERT INTO LIVRE VALUES ('CABA01','Nuit gravement au tabac','Essai','Francis Caballero');
INSERT INTO LIVRE VALUES ('LEVY03','Qui a tu� Daniel Pearl ?','Essai','Bernard-Henri L�vy');
INSERT INTO LIVRE VALUES ('DANT01','P�riph�riques','Essai','Maurice G. Dantec');
INSERT INTO LIVRE VALUES ('CHAU02','Rapporteur de guerre','Essai','Patrick Chauvel');
INSERT INTO LIVRE VALUES ('GUEN02','Plus fort que la haine','Essai','Tim Gu�nard');
INSERT INTO LIVRE VALUES ('BERG01','Laterna magica','Essai','Ingmar Bergman');
INSERT INTO LIVRE VALUES ('CYRU01','Les vilains petits canards','Essai','Boris Cyrulnik');
INSERT INTO LIVRE VALUES ('SEIT01','Le World Trade Center : une cible monumentale','Essai','Jean-Yves Andrieux et Fr�d�ric Seitz');
INSERT INTO LIVRE VALUES ('GARD01','Les formes de l''intelligence','Essai','Howard Gardner');
INSERT INTO LIVRE VALUES ('CYRU02','Les vilains petits canards','Essai','Boris Cyrulnik');
INSERT INTO LIVRE VALUES ('LOPE01','Le vampirisme au quotidien','Essai','G�rard Lopez');
INSERT INTO LIVRE VALUES ('BONN01','D�fi � la pudeur','Essai','G�rard Bonnet');
INSERT INTO LIVRE VALUES ('SHAN01','L''aventure des manuscrits de la mer Morte','Essai','Hershel Shanks');
INSERT INTO LIVRE VALUES ('GOYE02','Coll�ges de France','Essai','Mara Goyet');
INSERT INTO LIVRE VALUES ('GOYE03','Coll�ges de France','Essai','Mara Goyet');
INSERT INTO LIVRE VALUES ('COUR01','La France du rez-de-chauss�e','Essai','Jean-Fran�ois Courtille et Arman Maljaei-Courtille');
INSERT INTO LIVRE VALUES ('LABU01','A-ha, la v�rit� sur un groupe de l�gende','Essai','Laurent Labuche');
INSERT INTO LIVRE VALUES ('SERR01','Le Tiers-Instruit','Essai','Michel Serres');
INSERT INTO LIVRE VALUES ('COUR02','La France du rez-de-chauss�e','Essai','Jean-Fran�ois Courtille et Arman Maljaei-Courtille');
INSERT INTO LIVRE VALUES ('VICH01','Sans instructions','Essai','Laurence Vichnievsky');
INSERT INTO LIVRE VALUES ('INCH01','Main basse sur la musique','Essai','R�mi Godeau et Ir�ne Inchausp');
INSERT INTO LIVRE VALUES ('SOUA04','Br�l�e vive','Essai','Souad');
INSERT INTO LIVRE VALUES ('MAAL01','Les Identit�s meurtri�res','Essai','Amin Maalouf');
INSERT INTO LIVRE VALUES ('GOUG01','Les sept plumes de l''aigle','Essai','Henri Gougaud');
INSERT INTO LIVRE VALUES ('GOYE04','Coll�ges de France','Essai','Mara Goyet');
INSERT INTO LIVRE VALUES ('HERM01','Moi, Christiane F., 13 ans, drogu�e, prostitu�e','Essai','Kai Hermann');
INSERT INTO LIVRE VALUES ('COHE01','La Face cach�e du Monde','Essai','Pierre P�an, Philippe Cohen');
INSERT INTO LIVRE VALUES ('GRAN01','La vie d''autrefois dans le Tarn-et-Garonne','Essai','R�gis Granier');
INSERT INTO LIVRE VALUES ('MAAL02','Les identit�s meurtri�res','Essai','Amin Maalouf');
INSERT INTO LIVRE VALUES ('BURO01','Docteur, puis-je vous voir avant six mois ?','Essai','Nicole de Buron');
INSERT INTO LIVRE VALUES ('CADE01','Restavec, enfant esclave en Haiti','Essai','Jean-Robert Cadet');
INSERT INTO LIVRE VALUES ('ROUT01','L''Ange exterminateur','Essai','Airy Routier');
INSERT INTO LIVRE VALUES ('BARJ03','La Faim du tigre','Essai','Barjavel');
INSERT INTO LIVRE VALUES ('CASA01','L''aube rouge','Essai','Claire Casamby');
INSERT INTO LIVRE VALUES ('CASA02','L''aube rouge','Essai','Claire Casamby');
INSERT INTO LIVRE VALUES ('DEFO01','Survivre avec les loups','Essai','Misha Defonseca');
INSERT INTO LIVRE VALUES ('MANS01','The Long Hard Road Out of Hell','Essai','Marilyn Manson');
INSERT INTO LIVRE VALUES ('GIVA01','Le Non D�sir� - Dialogue avec l''enfant','Essai','Daniel Meurois-Givaudan');
INSERT INTO LIVRE VALUES ('AYAC01','Lettres a Prunelle','Essai','Alain Ayache');
INSERT INTO LIVRE VALUES ('GAAR01','Le myst�re de la patience','Essai','Josten Gaarder');
INSERT INTO LIVRE VALUES ('MILL01','C''est pour ton bien','Essai','Alice Miller');
INSERT INTO LIVRE VALUES ('NGER01','Chasses subtiles','Essai','Ernst Jünger');
INSERT INTO LIVRE VALUES ('TOLE01','Archimondain Jolipunk','Essai','Camille de Toledo');
INSERT INTO LIVRE VALUES ('AUST01','Je pensais que mon p�re �tait Dieu','Essai','Paul Auster');
INSERT INTO LIVRE VALUES ('CORE01','Mademoiselle sauve qui peut','Divers','Philippe Corentin');
INSERT INTO LIVRE VALUES ('ROWL01','Harry Potter ','Divers','Joanne K. Rowling');
INSERT INTO LIVRE VALUES ('UTTO01','Chhht','Divers','Salley Grindley et Peter Utton');
INSERT INTO LIVRE VALUES ('THOM02','P�lagie la sorci�re','Divers','Val�rie Thomas');
INSERT INTO LIVRE VALUES ('ROWL02','Harry Potter � l''�cole des sorciers','Divers','Joanne K. Rowling');
INSERT INTO LIVRE VALUES ('CHRI01','La trilogie des tripodes (3 livres)','Divers','John Christopher');
INSERT INTO LIVRE VALUES ('LASS01','Quand Papa avait mon �ge','Divers','Gilles Honotaux, H�l�ne Lasserre');
INSERT INTO LIVRE VALUES ('SEGU01','Un bon petit diable','Divers','La Comtesse de S�gur');
INSERT INTO LIVRE VALUES ('SEGU02','Les malheurs de Sophie','Divers','La Comtesse de S�gur');
INSERT INTO LIVRE VALUES ('SEGU03','Les petites filles mod�les','Divers','La Comtesse de S�gur');
INSERT INTO LIVRE VALUES ('RHOD01','Le prince de Central Park','Divers','Evan H. Rhodes');
INSERT INTO LIVRE VALUES ('NOZI01','Tu vaux mieux que mon fr�re','Divers','Nozi�re');
INSERT INTO LIVRE VALUES ('HONA01','Taxiphobie','Divers','Michel Honaker');
INSERT INTO LIVRE VALUES ('NOZI02','Eldorado','Divers','Jean-Paul Nozi�re');
INSERT INTO LIVRE VALUES ('MURA01','Golem, tome 2 : Joke','Divers','Marie-Aude Murail');
INSERT INTO LIVRE VALUES ('BOUR01','Une sorci�re cordon bleue','Divers','Patricia Bourque');
INSERT INTO LIVRE VALUES ('CABO01','Journal d''une princesse','Divers','Meg Cabot');
INSERT INTO LIVRE VALUES ('ARTH01','Parfum de sorci�re','Divers','Clair Arthur');
INSERT INTO LIVRE VALUES ('MURA02','Golem, tome 1 : Magic Berber','Divers','Marie-Aude Murail');
INSERT INTO LIVRE VALUES ('COLL02','Sur le sentier Maori','Divers','Collectif');
INSERT INTO LIVRE VALUES ('HEAR01','Le clan des Otori','Divers','Lian Hearn');
INSERT INTO LIVRE VALUES ('MIKS01','Le ruisseau aux larmes d''amour','Divers','Jean-Lucien Miksa');
INSERT INTO LIVRE VALUES ('COLL03','Sur le sentier Maori','Divers','Collectif');
INSERT INTO LIVRE VALUES ('DRUO01','Tistou les pouces verts','Divers','Maurice Druon');
INSERT INTO LIVRE VALUES ('THIO01','Hong Kong story','Divers','Anne Thiollier');
INSERT INTO LIVRE VALUES ('MOUR02','La rivi�re � l''envers','Divers','Jean-Claude Mourlevat');
INSERT INTO LIVRE VALUES ('CLAR01','Les plus belles histoires de Franklin ','Divers','Paulette Bourgeois et Brenda Clark');
INSERT INTO LIVRE VALUES ('KRIN01','Luce la puce','Divers','Antoon Krings');
INSERT INTO LIVRE VALUES ('MONC01','Georges Bouton, explomigrateur','Divers','G�rard Moncomble');
INSERT INTO LIVRE VALUES ('OPPE01','Silverwing','Divers','Kenneth Oppel');
INSERT INTO LIVRE VALUES ('SNIC01','Les d�sastreuses aventures des orphelins Baudelaire','Divers','Lemony Snicket');
INSERT INTO LIVRE VALUES ('DAHL01','Charlie et la chocolaterie','Divers','Roald Dahl');
INSERT INTO LIVRE VALUES ('MARE01','Esclave !','Divers','Pascale Maret');
INSERT INTO LIVRE VALUES ('ELSC01','Petite indienne Feuille-qui-Danse','Divers','G�raldine Elschner');
INSERT INTO LIVRE VALUES ('CLEM01','Seul dans la jungle','Divers','Yves-Marie Cl�ment');
INSERT INTO LIVRE VALUES ('SIMO01','Le livre de N�mo','Divers','Nicole Bacharan et Dominique Simonnet');
INSERT INTO LIVRE VALUES ('PELL01','L''inconnu du donjon','Divers','Evelyne Brisou-Pellen');
INSERT INTO LIVRE VALUES ('MORG01','La sixi�me','Divers','Susie Morgenstern');
INSERT INTO LIVRE VALUES ('NICH01','Les Secrets d''Aramanth','Divers','William Nicholson');
INSERT INTO LIVRE VALUES ('FARL01','Le fils de l''�talon noir','Divers','Walter Farley');
INSERT INTO LIVRE VALUES ('ROWL03','Harry Potter et la Coupe de feu','Divers','Joanne K. Rowling');
INSERT INTO LIVRE VALUES ('PULL01','A la crois�e des mondes','Divers','Philip Pullman');
INSERT INTO LIVRE VALUES ('BRAS01','Quatre filles et un jean','Divers','Ann Brashares');
INSERT INTO LIVRE VALUES ('HOLT01','Avez-vous vu Zachary Beaver ?','Divers','Kimberly Willis Holt');
INSERT INTO LIVRE VALUES ('MOKA01','L''enfant des ombres','Divers','Moka');
INSERT INTO LIVRE VALUES ('FRES01','Priv�s de t�l�','Divers','Gilles Fresse');
INSERT INTO LIVRE VALUES ('BRAS02','Quatre filles et un jean : Le deuxi�me �t�','Divers','Ann Brashares');
INSERT INTO LIVRE VALUES ('DAYR01','C''est la vie, Lili','Divers','Val�rie Dayre');
INSERT INTO LIVRE VALUES ('PERN01','Le journal secret de Marine','Divers','Sandrine Pernusch');
INSERT INTO LIVRE VALUES ('PIAS01','Ca d�m�nage  classe 104 !','Divers','Jerry Piasecki');
INSERT INTO LIVRE VALUES ('MCDA01','Et si c''�tait un ange ?','Divers','Lurlene McDaniel');
INSERT INTO LIVRE VALUES ('BRAS03','Quatre filles et un jean','Divers','Ann Brashares');
INSERT INTO LIVRE VALUES ('PLAC01','Le Royaume de Kensuk�','Divers','Michael Morpurgo et Fran�ois Place');
INSERT INTO LIVRE VALUES ('DANI01','Contes d''Afrique','Divers','Henri Gougaud, Marc Daniau');
INSERT INTO LIVRE VALUES ('HOMM01','Le Livre des �toiles','Divers','Erik L''Homme');
INSERT INTO LIVRE VALUES ('GAIM01','Coraline','Divers','Neil Gaiman');
INSERT INTO LIVRE VALUES ('CLEM02','Le puma aux yeux d''�meraude','Divers','Yves-Marie Cl�ment');
INSERT INTO LIVRE VALUES ('POUL01','Annabel et la B�te','Divers','Dominique Demers et St�phane Poulin');
INSERT INTO LIVRE VALUES ('POMM01','Avant la t�l�','Divers','Yvan Pommaux');
INSERT INTO LIVRE VALUES ('SEWE01','Black Beauty','Divers','Anna Sewell');
INSERT INTO LIVRE VALUES ('ROUX01','Le Chat qui �tait Lord','Divers','Laurent Rouxel');
INSERT INTO LIVRE VALUES ('MURA03','Magic Berber, golem tome 1','Divers','Elvire, Lorris et Marie-Aude Murail');
INSERT INTO LIVRE VALUES ('CANT01','Pas facile d''�tre une star','Divers','Marc Cantin');
INSERT INTO LIVRE VALUES ('MOUR03','L''enfant Oc�an','Divers','Jean-Claude Mourlevat');
INSERT INTO LIVRE VALUES ('BOUS01','La balle rouge','Divers','Patrick Bousquet');
INSERT INTO LIVRE VALUES ('BOUS02','Bleu, chien soleil des tranch�es','Divers','Patrick Bousquet');
INSERT INTO LIVRE VALUES ('PLAC02','Le vieux fou de dessins','Divers','Fran�ois Place');
INSERT INTO LIVRE VALUES ('BESS01','Arthur et les Minimoys','Divers','Luc Besson');
INSERT INTO LIVRE VALUES ('JALI01','Yack'' � lire de A � Z�bre ','Divers','Claire Benedetti et Maria Jalibert');
INSERT INTO LIVRE VALUES ('PEF01','Le monstre poilu','Divers','Henriette Bichonnier - Pef');
INSERT INTO LIVRE VALUES ('SORI01','Guide de la litt�rature pour la jeunesse','Divers','Marc Soriano');
INSERT INTO LIVRE VALUES ('SUSA01','Un petit fr�re pas comme les autres','Divers','Delval Marie-H�l�ne et Varley Susan');
INSERT INTO LIVRE VALUES ('DESM01','C''est �crit l�-haut','Divers','Catherine Desmarteau');
INSERT INTO LIVRE VALUES ('HOEY01','Hermux Tantamoq - Le temps ne s''arr�te pas pour les souris','Divers','Michaël Hoeye');
INSERT INTO LIVRE VALUES ('ALPA01','Lumina','Divers','Dan Alpac');
INSERT INTO LIVRE VALUES ('HERL01','Histoire du petit gar�on qui �tait une petite fille','Divers','Didier Herlem');
INSERT INTO LIVRE VALUES ('COLL04','Les Aventures de Pinocchio','Divers','Carlo Collodi');
INSERT INTO LIVRE VALUES ('CONV01','Les trois crimes d''Anubis','Divers','Didier Convard');
INSERT INTO LIVRE VALUES ('BROO01','Heartland, tome 7 : Le Champion bris�','Divers','Lauren Brooke');
INSERT INTO LIVRE VALUES ('BROO02','Heartland, num�ro 11 : La V�rit� ...ou presque','Divers','Lauren Brooke');
INSERT INTO LIVRE VALUES ('BROO03','Heartland, tome 1 : Je reste !','Divers','Lauren Brooke');
INSERT INTO LIVRE VALUES ('FREY01','Hector veut un chien','Divers','Nathalie Frey');
INSERT INTO LIVRE VALUES ('MURA04','Magic Berber, Golem, tome 1','Divers','Elvire Lorris et Marie-Aude Murail');
INSERT INTO LIVRE VALUES ('BLAK01','Caca boudin','Divers','Stephanie Blake');
INSERT INTO LIVRE VALUES ('MENS01','A table, Pr�sident !','Divers','Yann Mens');
INSERT INTO LIVRE VALUES ('EXUP01','Le Petit Prince','Divers','Antoine de Saint-Exup�ry');
INSERT INTO LIVRE VALUES ('KEAN01','J''ai �chang� mon p�re contre 2 poissons rouges','Divers','Neil Gaiman et Dave Mc Kean');
INSERT INTO LIVRE VALUES ('ERLB01','De la petite taupe qui voulait savoir qui lui avait fait sur la t�te','Divers','Werner Holzwarth/Wolf Erlbruch');
INSERT INTO LIVRE VALUES ('MAZA01','Je redessinerai le ciel bleu dans tes yeux','Divers','Claire Mazard');
INSERT INTO LIVRE VALUES ('COLF01','Artemis Fowl','Divers','Eoin Colfer');
INSERT INTO LIVRE VALUES ('NICH02','Les Secrets d''Aramanth - le Vent de Feu','Divers','William Nicholson');
INSERT INTO LIVRE VALUES ('PENN01','L''oeil du loup','Divers','Daniel Pennac');
INSERT INTO LIVRE VALUES ('AUBI01','Petit ours brun','Divers','Dani�le Bour, Marie Aubinais');
INSERT INTO LIVRE VALUES ('LAWR01','Coeur de loup','Divers','R.D. Lawrence');
INSERT INTO LIVRE VALUES ('PEF02','Le petit motordu','Divers','Pef');
INSERT INTO LIVRE VALUES ('GRAN02','L''empire des loups','Policier','Jean-Christophe Grang');
INSERT INTO LIVRE VALUES ('ELLR01','Am�rican Tablo�d','Policier','James Ellroy');
INSERT INTO LIVRE VALUES ('MANK01','Le guerrier solitaire','Policier','Henning Mankell');
INSERT INTO LIVRE VALUES ('BARB01','Les Kangourous','Policier','Dominque Barberis');
INSERT INTO LIVRE VALUES ('VACH01','Silence','Policier','Jeanne-Martine Vacher');
INSERT INTO LIVRE VALUES ('CARR01','Une petite bi�re, pour la route','Policier','Philippe Carrese');
INSERT INTO LIVRE VALUES ('PARO01','L''homme au ventre de plomb','Policier','Jean-Fran�ois Parot');
INSERT INTO LIVRE VALUES ('GRAN03','L''empire des loups','Policier','Jean-Christophe Grang');
INSERT INTO LIVRE VALUES ('MORI02','Les morts parlaient trop','Policier','Lucile Cl�mens-Morisset');
INSERT INTO LIVRE VALUES ('BENS01','Ne r�ve jamais de mourir','Policier','Raymond Benson');
INSERT INTO LIVRE VALUES ('LEHA01','T�n�bres, prenez-moi par la main ','Policier','Dennis Lehane');
INSERT INTO LIVRE VALUES ('JONQ01','Moloch','Policier','Thierry Jonquet');
INSERT INTO LIVRE VALUES ('SINI01','Femmes blafardes','Policier','Pierre Siniac');
INSERT INTO LIVRE VALUES ('COBE01','Ne le dis � personne','Policier','Harlan Coben');
INSERT INTO LIVRE VALUES ('INTE01','Cyber Poulpe','Policier','Collectif Internet');
INSERT INTO LIVRE VALUES ('EVAN01','La Prime','Policier','Janet Evanovich');
INSERT INTO LIVRE VALUES ('ELLR02','Le dalhia noir','Policier','James Ellroy');
INSERT INTO LIVRE VALUES ('XIAO01','Mort d''une h�roine rouge','Policier','Qiu Xiaolong');
INSERT INTO LIVRE VALUES ('VARG01','Pars vite et reviens tard','Policier','Fred Vargas');
INSERT INTO LIVRE VALUES ('CASE01','Genesis','Policier','John Case');
INSERT INTO LIVRE VALUES ('VARG02','Pars vite et reviens tard','Policier','Fred Vargas');
INSERT INTO LIVRE VALUES ('CAHR01','L''ali�niste','Policier','Caleb Cahr');
INSERT INTO LIVRE VALUES ('GRAN04','Le vol des cigognes','Policier','Jean-Christophe Grang');
INSERT INTO LIVRE VALUES ('LAHA01','Mystic River','Policier','Dennis Lahanne');
INSERT INTO LIVRE VALUES ('GRAN05','Les rivi�res pourpres','Policier','Christophe Grang');
INSERT INTO LIVRE VALUES ('VARG03','Pars vite et reviens tard','Policier','Fred Varga');
INSERT INTO LIVRE VALUES ('FERR01','Les Visages de Dieu','Policier','Jean-Denis Bruet-Ferreol');
INSERT INTO LIVRE VALUES ('FARR01','La ville de glace','Policier','John Farrow');
INSERT INTO LIVRE VALUES ('MAYN01','L''Heure du Diable','Policier','Bernard Olli�-Guy Maynart');
INSERT INTO LIVRE VALUES ('FERR02','Les Visages de Dieu','Policier','Jean-Denis Bruet-Ferreol');
INSERT INTO LIVRE VALUES ('LOUB01','Petits polars � l''usage des grands','Policier','Sophie Loubi�re');
INSERT INTO LIVRE VALUES ('DANT02','Les racines du mal','Policier','Maurice G. Dantec');
INSERT INTO LIVRE VALUES ('VARG04','L''homme � l''envers','Policier','Fred Vargas');
INSERT INTO LIVRE VALUES ('GRAN06','Le vol des cigognes','Policier','Jean-Christophe Grang');
INSERT INTO LIVRE VALUES ('MOOR05','La vestale � paillettes d Alualu','Policier','Christopher Moore');
INSERT INTO LIVRE VALUES ('BENA01','La machine � broyer les petites filles','Policier','Tonino Benacquista');
INSERT INTO LIVRE VALUES ('FERR03','Les visages de Dieu','Policier','Jean-Denis Bruet-Ferr�ol');
INSERT INTO LIVRE VALUES ('CARR02','L''ali�niste','Policier','Caleb Carr');
INSERT INTO LIVRE VALUES ('PAGA01','Derni�re station avant l''autoroute','Policier','Hugues Pagan');
INSERT INTO LIVRE VALUES ('ELLI01','American Psycho','Policier','Bret Easton Ellis');
INSERT INTO LIVRE VALUES ('NOTT01','Poison vert','Policier','Patric Nottret');
INSERT INTO LIVRE VALUES ('PARO02','L''�nigme des Blancs-Manteaux','Policier','Jean-Fran�ois Parot');
INSERT INTO LIVRE VALUES ('HEND01','Y''en a marre des blondes','Policier','Lauren Henderson');
INSERT INTO LIVRE VALUES ('BENA02','L''inconnue de Peshawar','Policier','Cheryl Benard');
INSERT INTO LIVRE VALUES ('ARNA01','La bo�te � chagrins','Policier','Philippe Arnaud');
INSERT INTO LIVRE VALUES ('AUBE01','La Mort dans le bois','Policier','Brigitte Aubert');
INSERT INTO LIVRE VALUES ('GUIN01','Le voleur de briquet','Policier','Michael Guinzburg');
INSERT INTO LIVRE VALUES ('BOYD01','L''apr�s-midi bleue','Policier','William Boyd');
INSERT INTO LIVRE VALUES ('LUDL01','Le pacte Cassandre','Policier','Robert Ludlum');
INSERT INTO LIVRE VALUES ('IZZO01','Total Kheops','Policier','Jean-Claude Izzo');
INSERT INTO LIVRE VALUES ('VAUT02','Le journal de Louise B.','Policier','Jean Vautrin');
INSERT INTO LIVRE VALUES ('MONF01','Commissaire Leon','Policier','Nadine Monfils');
INSERT INTO LIVRE VALUES ('MANK02','La cinqui�me femme','Policier','Henning Mankel');
INSERT INTO LIVRE VALUES ('AUBE02','Fun�rarium','Policier','Brigitte Aubert');
INSERT INTO LIVRE VALUES ('MANK03','Les morts de la Saint Jean','Policier','Henning Mankell');
INSERT INTO LIVRE VALUES ('RANK01','L''ombre du tueur','Policier','Ian Rankin');
INSERT INTO LIVRE VALUES ('PEIT01','Les Anges du Jugement','Policier','Claude Peitz');
INSERT INTO LIVRE VALUES ('KERR01','La tour d''Abraham','Policier','Philp Kerr');
INSERT INTO LIVRE VALUES ('CARR03','La constance du jardinier','Policier','John Le Carr');
INSERT INTO LIVRE VALUES ('GRAF01','N comme Naus�e','Policier','Sue Grafton');
INSERT INTO LIVRE VALUES ('FOLL01','Apocalypse sur commande','Policier','Ken Follet');
INSERT INTO LIVRE VALUES ('GRAN07','Les rivi�res pourpres','Policier','Christophe Grang');
INSERT INTO LIVRE VALUES ('GRIS01','L''Engrenage','Policier','John Grisham');
INSERT INTO LIVRE VALUES ('REVE02','Le tableau du ma�tre flamand','Policier','Arturo Perez Reverte');
INSERT INTO LIVRE VALUES ('CLAR02','Souviens-toi','Policier','Mary Higgins Clark');
INSERT INTO LIVRE VALUES ('THIR01','H�moglobine blues ','Policier','Philippe Thirault');
INSERT INTO LIVRE VALUES ('GRIS02','L''Affaire P�lican','Policier','John Grisham');
INSERT INTO LIVRE VALUES ('GERR01','Le Chirurgien','Policier','Tess Gerritsen');
INSERT INTO LIVRE VALUES ('BRUS01','L''Armure de vengeance','Policier','Serge Brussolo');
INSERT INTO LIVRE VALUES ('BELL01','Les assassins sont parmi nous','Policier','Pierre Bellemare');
INSERT INTO LIVRE VALUES ('GEOR01','M�moire infid�le','Policier','Elisabeth George');
INSERT INTO LIVRE VALUES ('AUBE03','La mort des bois','Policier','Brigitte Aubert');
INSERT INTO LIVRE VALUES ('PENN02','La F�e carabine','Policier','Daniel Pennac');
INSERT INTO LIVRE VALUES ('KING01','Dolores Claiborne','Policier','Stephen King');
INSERT INTO LIVRE VALUES ('GRIS03','Pas de Noël cette ann�e','Policier','John Grisham');
INSERT INTO LIVRE VALUES ('DANT03','La Sir�ne rouge','Policier','Maurice G. Dantec');
INSERT INTO LIVRE VALUES ('BESS02','Meurtres � l''antique','Policier','Yvonne Besson');
INSERT INTO LIVRE VALUES ('FAIL01','On a vol� la Belle-�toile','Policier','Jean Failler');
INSERT INTO LIVRE VALUES ('COBE02','Ne le dis � personne','Policier','Harlan Coben');
INSERT INTO LIVRE VALUES ('GRAN08','Le Concile de pierre','Policier','Jean-Christophe Grang');
INSERT INTO LIVRE VALUES ('NEVI01','Le Huit','Policier','Katherine Neville');
INSERT INTO LIVRE VALUES ('COBE03','Ne le dis � personne','Policier','Harlan Coben');
INSERT INTO LIVRE VALUES ('HARR01','Dragon Rouge','Policier','Thomas Harrys');
INSERT INTO LIVRE VALUES ('BRUS02','Le labyrinthe de Pharaon','Policier','Serge Brussolo');
INSERT INTO LIVRE VALUES ('POSA01','Cinq mouches bleues','Policier','Carmen Posadas');
INSERT INTO LIVRE VALUES ('CRES01','Chasseurs de t�tes','Policier','Michel Crespy');
INSERT INTO LIVRE VALUES ('GRAN09','Double je','Policier','Sylvie Granotier');
INSERT INTO LIVRE VALUES ('FARR02','Le lac de glace','Policier','John Farrow');
INSERT INTO LIVRE VALUES ('JOYA01','Plaisir en bouche','Policier','B�atrice Joyau');
INSERT INTO LIVRE VALUES ('CARR04','L''adversaire','Policier','Emmanuel Carr�re');
INSERT INTO LIVRE VALUES ('GRAF02','A comme alibi','Policier','Sue Grafton');
INSERT INTO LIVRE VALUES ('GEOR02','M�moire infid�le','Policier','Elisabeth George');
INSERT INTO LIVRE VALUES ('REVE03','La reine du Sud','Policier','Arturo P�rez-Reverte');
INSERT INTO LIVRE VALUES ('VARG05','Debout les morts','Policier','Fred Vargas');
INSERT INTO LIVRE VALUES ('CONN01','La glace noire','Policier','Michael Connelly');
INSERT INTO LIVRE VALUES ('COBE04','Une chance de trop','Policier','Harlan Coben');
INSERT INTO LIVRE VALUES ('CONN02','Le po�te','Policier','Michael Connelly');
INSERT INTO LIVRE VALUES ('PERR01','Pass� sous silence','Policier','Anne Perry');
INSERT INTO LIVRE VALUES ('MACD01','Origine suspecte','Policier','Patricia MacDonald');
INSERT INTO LIVRE VALUES ('GRAN10','Le Concile de pierre','Policier','Jean-Christophe Grang');
INSERT INTO LIVRE VALUES ('CONN03','Wonderland Avenue','Policier','Michael Connely');
INSERT INTO LIVRE VALUES ('FOLL02','Les pilliers de la terre','Policier','Ken Follet');
INSERT INTO LIVRE VALUES ('CLAN01','Jeux de guerre','Policier','Tom Clancy');
INSERT INTO LIVRE VALUES ('ELLR03','Le Grand Nulle Part','Policier','James Ellroy');
INSERT INTO LIVRE VALUES ('CAPO01','De  sang froid','Policier','Truman Capote');
INSERT INTO LIVRE VALUES ('VARG06','Pars vite et reviens tard','Policier','Fred Vargas');
INSERT INTO LIVRE VALUES ('FERR04','Les Visages de Dieu','Policier','Jean-Denis Bruet-Ferr�ol');
INSERT INTO LIVRE VALUES ('FARR03','La ville de glace','Policier','John Farrow');
INSERT INTO LIVRE VALUES ('CONN04','Le Po�te','Policier','Michael Connelly');
INSERT INTO LIVRE VALUES ('HARR02','Le silence des agneaux','Policier','Thomas Harris');
INSERT INTO LIVRE VALUES ('CHRI02','Les dix petits n�gres','Policier','Agatha Christie');
INSERT INTO LIVRE VALUES ('VIVI01','Blanc chemin','Policier','Moor Viviane');
INSERT INTO LIVRE VALUES ('VIVI02','Rouge sombre','Policier','Moore Viviane');
INSERT INTO LIVRE VALUES ('MORG02','L''alchimiste assassin�','Policier','Fidelis Morgan');
INSERT INTO LIVRE VALUES ('ELTO01','Devine qui vient mourir ce soir ?','Policier','Ben Elton');
INSERT INTO LIVRE VALUES ('LEHA02','Gone, baby, gone','Policier','Dennis Lehane');
INSERT INTO LIVRE VALUES ('PERR02','La marque de Ca�n','Policier','Anne Perry');
INSERT INTO LIVRE VALUES ('COBE05','Disparu � jamais','Policier','Harlan Coben');
INSERT INTO LIVRE VALUES ('COLL05','La dame en blanc','Policier','Wilkie Collins');
INSERT INTO LIVRE VALUES ('WALT02','Chambre froide','Policier','Minette Walters');
INSERT INTO LIVRE VALUES ('XIAO02','Mort d''une h�ro�ne rouge','Policier','Qiu Xiaolong');
INSERT INTO LIVRE VALUES ('COBE06','Ne le dis � personne','Policier','Harlan Coben');
INSERT INTO LIVRE VALUES ('CONN05','Cr�ance de sang','Policier','Michael Connelly');
INSERT INTO LIVRE VALUES ('MACD02','Moralit� douteuse','Policier','Bonnie MacDougal');
INSERT INTO LIVRE VALUES ('RULE01','Sans nouvelles de toi','Policier','Ann Rule');
INSERT INTO LIVRE VALUES ('ALVT01','Recherch�e','Policier','Karin Alvtegen');
INSERT INTO LIVRE VALUES ('BRUS03','Les emmur�s','Policier','Serge Brussolo');
INSERT INTO LIVRE VALUES ('CONN06','Laissez toute esp�rance','Policier','John Connolly');
INSERT INTO LIVRE VALUES ('COBE07','Disparu � jamais','Policier','Harlan Coben');
INSERT INTO LIVRE VALUES ('GRAN11','L''empire des loups','Policier','Jean-Christophe Grang');
INSERT INTO LIVRE VALUES ('CONN07','Cr�ance de sang','Policier','Michael Connelly');
INSERT INTO LIVRE VALUES ('GEOR03','Pour solde de tout compte','Policier','Elizabeth George');
INSERT INTO LIVRE VALUES ('GRAN12','L''empire des loups','Policier','Jean-Christophe Grang');
INSERT INTO LIVRE VALUES ('FREN01','La chambre �carlate','Policier','Nicci French');
INSERT INTO LIVRE VALUES ('COBE08','Disparu � jamais','Policier','Harlan Coben');
INSERT INTO LIVRE VALUES ('COBE09','Ne le dis � personne','Policier','Harlan Coben');
INSERT INTO LIVRE VALUES ('CORN01','Dossier Benton','Policier','Patricia Cornwell');
INSERT INTO LIVRE VALUES ('SATI01','A la recherche de Rita Kemper','Policier','Luna Satie');
INSERT INTO LIVRE VALUES ('COBE10','Ne le dis � personne','Policier','Harlan Coben');
INSERT INTO LIVRE VALUES ('GIES01','L''abatteur','Policier','Franz-Olivier Giesbert');
INSERT INTO LIVRE VALUES ('LEHA03','Sacr�','Policier','Dennis Lehane');
INSERT INTO LIVRE VALUES ('FOLL03','Le troisi�me jumeau','Policier','Ken Follett');
INSERT INTO LIVRE VALUES ('SCOP01','Donato p�re et fille','Policier','Sandra Scoppettone');
INSERT INTO LIVRE VALUES ('CHAT01','L''�me du mal','Policier','Maxime Chattam');
INSERT INTO LIVRE VALUES ('FREN02','Feu de glace','Policier','Nicci French');
INSERT INTO LIVRE VALUES ('COBE11','Rupture de contrat','Policier','Harlan Coben');
INSERT INTO LIVRE VALUES ('EDWA01','Danse avec l''ange','Policier','Ake Edwardson');
INSERT INTO LIVRE VALUES ('LEHA04','Mystic River','Policier','Dennis Lehane');
INSERT INTO LIVRE VALUES ('SCOP02','Tout ce qui est � toi...','Policier','Sandra Scoppettone');
INSERT INTO LIVRE VALUES ('LUDL02','La m�moire dans la peau','Policier','Robert Ludlum');
INSERT INTO LIVRE VALUES ('GIES02','L''abatteur','Policier','Franz-Olivier Giesbert');
INSERT INTO LIVRE VALUES ('CARR05','L''ali�niste','Policier','Caleb Carr');
INSERT INTO LIVRE VALUES ('ELLR04','Le dahlia noir','Policier','James Ellroy');
INSERT INTO LIVRE VALUES ('COBE12','Ne le dis � personne','Policier','Harlan Coben');
INSERT INTO LIVRE VALUES ('CASE02','Genesis','Policier','John Case');
INSERT INTO LIVRE VALUES ('LEHA05','Gone, baby, gone','Policier','Dennis Lehane');
INSERT INTO LIVRE VALUES ('MANK04','La muraille invisible','Policier','Henning Mankell');
INSERT INTO LIVRE VALUES ('CHAT02','L''�me du mal','Policier','Maxime Chattam');
INSERT INTO LIVRE VALUES ('CONN08','Darling Lilly','Policier','Michael Connelly');
INSERT INTO LIVRE VALUES ('LEON01','L''affaire Paola','Policier','Donna Leon');
INSERT INTO LIVRE VALUES ('CHAT03','L''�me du mal','Policier','Maxime Chattam');
INSERT INTO LIVRE VALUES ('LIEB01','Le vagabond de Holmby Park','Policier','Herbert H. Lieberman');
INSERT INTO LIVRE VALUES ('REND01','Danger de mort','Policier','Ruth Rendell');
INSERT INTO LIVRE VALUES ('DURA01','Daddy','Policier','Loup Durand');
INSERT INTO LIVRE VALUES ('PERR03','Le bourreau de Hyde Park','Policier','Anne Perry');
INSERT INTO LIVRE VALUES ('MCDE01','Le tueur des ombres','Policier','Val McDermid');
INSERT INTO LIVRE VALUES ('REND02','Danger de mort','Policier','Ruth Rendell');
INSERT INTO LIVRE VALUES ('CHRI03','La troisi�me fille','Policier','Agatha Christie');
INSERT INTO LIVRE VALUES ('LETE01','Pi�ges','Policier','Dominique Letellier');
INSERT INTO LIVRE VALUES ('GUYA01','Op�ration Madelone','Policier','Yannick Le Guyadec');
INSERT INTO LIVRE VALUES ('GRAN13','Le Concile de pierre','Policier','Jean-Christophe Grang');
INSERT INTO LIVRE VALUES ('GRAN14','Les Rivi�res pourpres','Policier','Jean-Christophe Grang');
INSERT INTO LIVRE VALUES ('GRAN15','Le vol des cigognes','Policier','Jean-Christophe Grang');
INSERT INTO LIVRE VALUES ('ROCH01','Les Vautours blancs','Policier','Jean-Jacques Roche');
INSERT INTO LIVRE VALUES ('POUY01','H4 Blues','Policier','Jean-Bernard Pouy');
INSERT INTO LIVRE VALUES ('WEST01','Le couperet','Policier','Donald Edwin Westlake');
INSERT INTO LIVRE VALUES ('COBE13','Disparu � jamais','Policier','Harlan Coben');
INSERT INTO LIVRE VALUES ('MART01','Descente en eaux troubles','Policier','Julia Wallis Martin');
INSERT INTO LIVRE VALUES ('BERN01','Fant�mes','Policier','Ma�t� Bernard');
INSERT INTO LIVRE VALUES ('COLL06','La pierre de lune','Policier','W. Wilkie Collins');
INSERT INTO LIVRE VALUES ('ELLI02','Une femme en danger','Policier','James Elliot');
INSERT INTO LIVRE VALUES ('CLAR03','La maison du clair de lune','Policier','Mary Higgins Clark');
INSERT INTO LIVRE VALUES ('LEON02','Des amis hauts plac�s','Policier','Donna Leon');
INSERT INTO LIVRE VALUES ('CONN09','Le Po�te','Policier','Michael Connelly');
INSERT INTO LIVRE VALUES ('BORR01','L''ombre du chat','Policier','Paul Borrelli');
INSERT INTO LIVRE VALUES ('BOIS01','Marie-Temp�te','Litt�rature','Janine Boissard');
INSERT INTO LIVRE VALUES ('SKIN01','Le parfum','Litt�rature','Patrick Süskind');
INSERT INTO LIVRE VALUES ('COEL01','L''alchimiste','Litt�rature','Paulo Coelho');
INSERT INTO LIVRE VALUES ('ARVO01','Les enfants de l''aube','Litt�rature','Patrick Poivre d''Arvor');
INSERT INTO LIVRE VALUES ('TUIL01','Interdit','Litt�rature','Karine Tuil');
INSERT INTO LIVRE VALUES ('PADU01','Le Palmier et l''Etoile ','Litt�rature','Leonardo Padura');
INSERT INTO LIVRE VALUES ('SEPU01','Le vieux qui lisait des romans d''amour','Litt�rature','Luis Sepúlveda');
INSERT INTO LIVRE VALUES ('POTO01','L''Elu','Litt�rature','Cha�m Potok');
INSERT INTO LIVRE VALUES ('SCHM01','Monsieur Ibrahim et les fleurs du Coran','Litt�rature','Eric-Emmanuel Schmitt');
INSERT INTO LIVRE VALUES ('SIGN01','Les cailloux bleus','Litt�rature','Christian Signol');
INSERT INTO LIVRE VALUES ('NOTH01','Mercure','Litt�rature','Am�lie Nothomb');
INSERT INTO LIVRE VALUES ('GENE01','Raboliot','Litt�rature','Maurice Genevoix');
INSERT INTO LIVRE VALUES ('ETXE01','Amour, Prozac, et autres curiosit�s','Litt�rature','Lucia Etxebarria');
INSERT INTO LIVRE VALUES ('BOUL01','Eux les vaches, nous les porcs','Litt�rature','Carmen Boullosa');
INSERT INTO LIVRE VALUES ('ZOLA01','Au bonheur des dames','Litt�rature','Emile Zola');
INSERT INTO LIVRE VALUES ('ALLE01','Portrait s�pia','Litt�rature','Isabel Allende');
INSERT INTO LIVRE VALUES ('GAVA01','Je l''aimais','Litt�rature','Anna Gavalda');
INSERT INTO LIVRE VALUES ('LEVY04','Et si c''�tait vrai...','Litt�rature','Marc Levy');
INSERT INTO LIVRE VALUES ('GAIL01','Un soir au club','Litt�rature','Christian Gailly');
INSERT INTO LIVRE VALUES ('DUPE01','Allons voir plus loin, veux tu ?','Litt�rature','Anny Duperey');
INSERT INTO LIVRE VALUES ('BEIG01','Windows on the world','Litt�rature','Fr�d�ric Beigbeder');
INSERT INTO LIVRE VALUES ('LACL01','Les Liaisons dangereuses','Litt�rature','Pierre-Ambroise-Fran�ois Choderlos de Laclos');
INSERT INTO LIVRE VALUES ('DAVE01','Les fr�res Holt','Litt�rature','Marcia Davenport');
INSERT INTO LIVRE VALUES ('YICH01','T�te-b�che','Litt�rature','Liu Yichang');
INSERT INTO LIVRE VALUES ('BENA03','Quelqu''un d''autre','Litt�rature','Tonino Benacquista');
INSERT INTO LIVRE VALUES ('SIDD01','De l''autre c�t� de l''�le','Litt�rature','Anne Rivers Siddons');
INSERT INTO LIVRE VALUES ('NOTH02','Cosm�tique de l''ennemi','Litt�rature','Am�lie Nothomb');
INSERT INTO LIVRE VALUES ('ORSE01','Madame B�','Litt�rature','Erik Orsenna');
INSERT INTO LIVRE VALUES ('SA01','La joueuse de go','Litt�rature','Shan Sa');
INSERT INTO LIVRE VALUES ('WERB02','Le livre du voyage','Litt�rature','Bernard Werber');
INSERT INTO LIVRE VALUES ('BRUN01','La tentation d''Edouard','Litt�rature','Elisa Brune');
INSERT INTO LIVRE VALUES ('BARJ04','Le grand secret','Litt�rature','Ren� Barjavel');
INSERT INTO LIVRE VALUES ('KOUR01','Le Pingouin','Litt�rature','Andre� Kourkov');
INSERT INTO LIVRE VALUES ('GAGN01','La femme patiente','Litt�rature','Alain Gagnol');
INSERT INTO LIVRE VALUES ('COLO01','El Guanaco','Litt�rature','Francisco Coloane');
INSERT INTO LIVRE VALUES ('MERL01','L''�le','Litt�rature','Robert Merle');
INSERT INTO LIVRE VALUES ('COEL02','Onze minutes','Litt�rature','Paolo Coelho');
INSERT INTO LIVRE VALUES ('LAFO01','Une fi�vre impossible � n�gocier','Litt�rature','Lola Lafon');
INSERT INTO LIVRE VALUES ('UDAL01','Le destin miraculeux d''Edgar Mint','Litt�rature','Brady Udall');
INSERT INTO LIVRE VALUES ('MARA01','L''h�ritage d''Esther','Litt�rature','Sandor Marai');
INSERT INTO LIVRE VALUES ('MIHA01','L''accident','Litt�rature','S�bastien Mihail');
INSERT INTO LIVRE VALUES ('NOTH03','Hygi�ne de l''assassin','Litt�rature','Am�lie Nothomb');
INSERT INTO LIVRE VALUES ('MAAS01','Noces indiennes','Litt�rature','Sharon Maas');
INSERT INTO LIVRE VALUES ('SMIT01','Sourires de Loup','Litt�rature','Zadie Smith');
INSERT INTO LIVRE VALUES ('WAGN01','Graine d''ortie','Litt�rature','Paul Wagner');
INSERT INTO LIVRE VALUES ('COUA01','Soeur Am�re','Litt�rature','Mireille Couant');
INSERT INTO LIVRE VALUES ('FERM01','Neige','Litt�rature','Maxence Fermine');
INSERT INTO LIVRE VALUES ('MORG03','Le Bleu de la mer','Litt�rature','C�dric Morgan');
INSERT INTO LIVRE VALUES ('BOIS02','Rendez-vous avec mon fils','Litt�rature','Janine Boissard');
INSERT INTO LIVRE VALUES ('KENN01','Une relation dangereuse','Litt�rature','Douglas Kennedy');
INSERT INTO LIVRE VALUES ('ROSA01','Mon ange','Litt�rature','Guillermo Rosales');
INSERT INTO LIVRE VALUES ('SRIE01','L�gende Indon�sienne','Litt�rature','Virginie Srienz');
INSERT INTO LIVRE VALUES ('MONT01','l''arbre aux secrets','Litt�rature','Santa Montefiore');
INSERT INTO LIVRE VALUES ('JOYC01','La v�rit� sur Kate Gallagher','Litt�rature','Brenda Joyce');
INSERT INTO LIVRE VALUES ('SEBO01','La nostalgie de l''ange','Litt�rature','Alice Sebold');
INSERT INTO LIVRE VALUES ('CERV01','Don Quichotte de la Manche','Litt�rature','Miguel de Cervant�s');
INSERT INTO LIVRE VALUES ('PICO01','Pour que justice soit faite','Litt�rature','Jodi Picoult');
INSERT INTO LIVRE VALUES ('FILI01','Les derniers jours de la classe ouvri�re','Litt�rature','Aur�lie Filippetti');
INSERT INTO LIVRE VALUES ('DELE01','La premi�re gorg�e de bi�re','Litt�rature','Philippe Delerm');
INSERT INTO LIVRE VALUES ('RAND01','la source vive ','Litt�rature','Ayn Rand');
INSERT INTO LIVRE VALUES ('HORN01','Haute fid�lit�','Litt�rature','Nick Hornby');
INSERT INTO LIVRE VALUES ('ARMA01','Au bonheur du matin','Litt�rature','Marie-Paul Armand');
INSERT INTO LIVRE VALUES ('FIEL01','Ne compte pas les heures','Litt�rature','Joy Fielding');
INSERT INTO LIVRE VALUES ('KOB01','La femme des sables','Litt�rature','Ab� K�b');
INSERT INTO LIVRE VALUES ('HAUS02','Le mur invisible','Litt�rature','Marlen Haushofer');
INSERT INTO LIVRE VALUES ('ALLE02','Portrait s�pia','Litt�rature','Isabel Allende');
INSERT INTO LIVRE VALUES ('TAN01','Le club de la chance','Litt�rature','Amy Tan');
INSERT INTO LIVRE VALUES ('GAYL01','Trente ans d�j�','Litt�rature','Mike Gayle');
INSERT INTO LIVRE VALUES ('ZOLA02','Germinal','Litt�rature','Emile Zola');
INSERT INTO LIVRE VALUES ('ECO02','Le nom de la rose','Litt�rature','Umberto Eco');
INSERT INTO LIVRE VALUES ('PAGE01','Comment je suis devenu stupide','Litt�rature','Martin Page');
INSERT INTO LIVRE VALUES ('CHEV01','La jeune fille � la perle','Litt�rature','Tracy Chevalier');
INSERT INTO LIVRE VALUES ('EVSK01','Crime et ch�timent','Litt�rature','Fedor Mikha�lovitch Dosto�evski');
INSERT INTO LIVRE VALUES ('GIBR03','Le proph�te','Litt�rature','Khalil Gibran');
INSERT INTO LIVRE VALUES ('SYDR01','D''arches, et d''alliances','Litt�rature','Carole de Sydrac');
INSERT INTO LIVRE VALUES ('MOIG01','Temp�te sur le Gu�pratte','Litt�rature','Christine Grelet - Le Moigne');
INSERT INTO LIVRE VALUES ('NOTH05','Stupeurs et tremblements','Litt�rature','Am�lie Nothomb');
INSERT INTO LIVRE VALUES ('LAMO01','Il y a des vies...','Litt�rature','Delphine Lamotte');
INSERT INTO LIVRE VALUES ('HORN02','Pour un gar�on','Litt�rature','Nick Hornby');
INSERT INTO LIVRE VALUES ('ARMA02','Au bonheur du matin','Litt�rature','Marie-Paul Armand');
INSERT INTO LIVRE VALUES ('EVAN02','Le coeur des flammes','Litt�rature','Nicholas Evans');
INSERT INTO LIVRE VALUES ('CARR06','Le bal des Cagoles','Litt�rature','Philippe Carrese');
INSERT INTO LIVRE VALUES ('DURR01','Le quatuor d''Alexandrie','Litt�rature','Lawrence Durrell');
INSERT INTO LIVRE VALUES ('HOME01','Lady Love','Litt�rature','Homeric');
INSERT INTO LIVRE VALUES ('SCHO01','L''aile du papillon','Litt�rature','Pierre Schoendoerffer');
INSERT INTO LIVRE VALUES ('CAUW03','L''�ducation d''une f�e','Litt�rature','Didier Van Cauwelaert');
INSERT INTO LIVRE VALUES ('HARU01','Le chant des plaines','Litt�rature','Kent Haruf');
INSERT INTO LIVRE VALUES ('BESS03','Un gar�on d''Italie','Litt�rature','Philippe Besson');
INSERT INTO LIVRE VALUES ('HARR03','Vin de boh�me','Litt�rature','Joanne Harris');
INSERT INTO LIVRE VALUES ('TOSC01','La main de Dante','Litt�rature','Nick Tosches');
INSERT INTO LIVRE VALUES ('COE01','Testament � l''anglaise','Litt�rature','Jonathan Coe');
INSERT INTO LIVRE VALUES ('PENN03','Le dictateur et le hamac','Litt�rature','Daniel Pennac');
INSERT INTO LIVRE VALUES ('ATWO01','Le tueur aveugle','Litt�rature','Margaret Atwood');
INSERT INTO LIVRE VALUES ('KASM01','Le cimeti�re de verre','Litt�rature','Sorour Kasma');
INSERT INTO LIVRE VALUES ('LEVY05','Et si c''�tait vrai...','Litt�rature','Marc Levy');
INSERT INTO LIVRE VALUES ('TEST01','Il n''y a pas beaucoup d''�toiles ce soir','Litt�rature','Sylvie Testud');
INSERT INTO LIVRE VALUES ('RUFF01','L''Abyssin','Divers','Jean-Cristophe Ruffin');
INSERT INTO LIVRE VALUES ('FERG01','Mille femmes blanches','Divers','Jim Fergus');
INSERT INTO LIVRE VALUES ('STEE02','Zoya','Divers','Danielle Steel');
INSERT INTO LIVRE VALUES ('HUYS01','L�-Bas ','Divers','Joris-Karl Huysmans');
INSERT INTO LIVRE VALUES ('VIVA01','La Cath�drale au fond du jardin','Divers','Maxime Vivas');
INSERT INTO LIVRE VALUES ('YOUR01','L''Oeuvre au Noir','Divers','Marguerite Yourcenar');
INSERT INTO LIVRE VALUES ('DRUO02','Les Rois maudits','Divers','Maurice Druon');
INSERT INTO LIVRE VALUES ('HALT01','Le vent des Kazars','Divers','Marek Halter');
INSERT INTO LIVRE VALUES ('FOLL04','la marque de Windfield','Divers','Ken Follet');
INSERT INTO LIVRE VALUES ('CHAL01','Chere Marie-Antoinette','Divers','Jean Chalon');
INSERT INTO LIVRE VALUES ('FOLL05','Les Pilliers de la Terre','Divers','Ken Follett');
INSERT INTO LIVRE VALUES ('NGUY01','La nuit nous a surpris ','Divers','Kien Nguyen');
INSERT INTO LIVRE VALUES ('PEYR01','Les chiens sauvages ','Divers','Michel Peyramaure');
INSERT INTO LIVRE VALUES ('ADKI01','The Keys of Egypt','Divers','Lesley and Roy Adkins');
INSERT INTO LIVRE VALUES ('LUND01','Pomp�i','Divers','Maja Lundgren');
INSERT INTO LIVRE VALUES ('LEVI01','Si c''est un homme','Divers','Primo Levi');
INSERT INTO LIVRE VALUES ('CALM01','Le lit d''Alienor','Divers','Mireille Calmel');
INSERT INTO LIVRE VALUES ('PERE01','Les Trois mousquetaires','Divers','Alexandre Dumas (p�re');
INSERT INTO LIVRE VALUES ('GALL01','Napoleon','Divers','Max Gallo');
INSERT INTO LIVRE VALUES ('DUFO01','Marie-Antoinette, la mal aim�e','Divers','Hortense Dufour');
INSERT INTO LIVRE VALUES ('RUFI01','Rouge Br�sil','Divers','Jean-Christophe Rufin');
INSERT INTO LIVRE VALUES ('BRIA01','L''Ile de la d�solation','Divers','Patrick O Brian');
INSERT INTO LIVRE VALUES ('PARO04','L''affaire Nicolas Le Floch','Divers','Jean-Fran�ois Parot');
INSERT INTO LIVRE VALUES ('CALM02','Le bal des louves','Divers','Mireille Calmel');
INSERT INTO LIVRE VALUES ('MAHF02','Le jardin du pass�','Divers','Naguib Mahfouz');
INSERT INTO LIVRE VALUES ('SA02','La joueuse de go','Divers','Shan Sa');
INSERT INTO LIVRE VALUES ('KERC01','Mon p�re, ce harki','Divers','Dalila Kerchouche');
INSERT INTO LIVRE VALUES ('BRIA02','Capitaine de vaisseau','Divers','Patrick O''Brian');
INSERT INTO LIVRE VALUES ('MICH01','Des grives aux loups','Divers','Claude Michelet');
INSERT INTO LIVRE VALUES ('NAUD02','Le Cycle Tristan de Castelreng','Divers','Pierre Naudin');
INSERT INTO LIVRE VALUES ('ARMA04','Le pain rouge','Divers','Marie-Paul Armand');
INSERT INTO LIVRE VALUES ('SA03','La joueuse de go','Divers','Shan Sa');
INSERT INTO LIVRE VALUES ('CALM03','Le bal des louves','Divers','Mireille Calmel');
INSERT INTO LIVRE VALUES ('LEVY06','Le pass� d''une innocence ','Divers','Laurent L�vy');
INSERT INTO LIVRE VALUES ('VINC01','Le pape des escargots','Divers','Henri Vincenot');
INSERT INTO LIVRE VALUES ('FOLL06','Les piliers de la terre','Divers','Ken Follett');
INSERT INTO LIVRE VALUES ('TIRT02','Le passeur de lumi�re','Divers','Bernard Tirtiaux');
INSERT INTO LIVRE VALUES ('AUEL04','Les refuges de pierre','Divers','Jean M. Auel');
INSERT INTO LIVRE VALUES ('BOUT01','Sang Breton','Divers','Michel Bouts');
INSERT INTO LIVRE VALUES ('COND01','Moi, Tituba sorci�re','Divers','Maryse Cond');
INSERT INTO LIVRE VALUES ('JACQ03','Rams�s','Divers','Christian Jacq');
INSERT INTO LIVRE VALUES ('MOAT01','Villa Jasmin','Divers','Serge Moati');
INSERT INTO LIVRE VALUES ('HALT02','La Bible au f�minin : Sarah','Divers','Marek Halter');
INSERT INTO LIVRE VALUES ('SA04','Imp�ratrice','Divers','Shan Sa');
INSERT INTO LIVRE VALUES ('LLOS01','Le Paradis, un peu plus loin','Divers','Mario Vargas Llosa');
INSERT INTO LIVRE VALUES ('REDF01','La musique des sph�res','Divers','Elizabeth Redfern');
INSERT INTO LIVRE VALUES ('FREC01','Les chevaux c�lestes','Divers','Jos� Fr�ches');
INSERT INTO LIVRE VALUES ('SORT01','Imprimatur','Divers','Rita Monaldi et Francesco Sorti');
INSERT INTO LIVRE VALUES ('MART02','La relique','Divers','Jean-Louis Marteil');
INSERT INTO LIVRE VALUES ('MAAL04','Le p�riple de Baldassare','Divers','Amin Maalouf');
INSERT INTO LIVRE VALUES ('AUEL05','Les Enfants de la Terre','Divers','Jean M. Auel');
INSERT INTO LIVRE VALUES ('MAAL05','L�on L''Africain','Divers','Amin Maalouf');
INSERT INTO LIVRE VALUES ('HAMB01','La poussi�re des ombres','Divers','Barbara Hambly');
INSERT INTO LIVRE VALUES ('YVEL01','Saisons sans voix','Divers','Stephan Yveline');
INSERT INTO LIVRE VALUES ('YVEL02','Un voile rouge � la surface des vagues','Divers','Stephan Yveline');
INSERT INTO LIVRE VALUES ('BENZ02','Thibaut ou la croix perdue (Les Chevaliers, tome 1)','Divers','Juliette Benzoni');
INSERT INTO LIVRE VALUES ('DIDI01','Mes conversations avec la Reine','Divers','Yaguel Didier');
INSERT INTO LIVRE VALUES ('BRUS04','le labyrinthe de pharaon','Divers','Serge Brussolo');
INSERT INTO LIVRE VALUES ('JACQ06','Rams�s','Divers','Christians Jacq');
INSERT INTO LIVRE VALUES ('REVE04','L''Or du roi','Divers','Arturo Perez-Reverte');
INSERT INTO LIVRE VALUES ('FOLL08','Le R�seau Corneille','Divers','Ken Follet');
INSERT INTO LIVRE VALUES ('FERG03','Mille femmes blanches','Divers','Jim Fergus');
INSERT INTO LIVRE VALUES ('MERL04','Fortune de France','Divers','Robert Merle');
INSERT INTO LIVRE VALUES ('PRAT02','Le huiti�me sortil�ge','SF','Terry Pratchett');
INSERT INTO LIVRE VALUES ('ESCH01','J�sus Vid�o','SF','Andr�as Eschbach');
INSERT INTO LIVRE VALUES ('GREN01','Virus LIV-3 ou la Mort des livres','SF','Christian Grenier');
INSERT INTO LIVRE VALUES ('WERB03','Les Thanatonautes','SF','Bernard Werber');
INSERT INTO LIVRE VALUES ('BESS04','Arthur et les minnimoy','SF','Luc Besson');
INSERT INTO LIVRE VALUES ('FEIS01','Pug l''apprenti','SF','Raymond E. Feist');
INSERT INTO LIVRE VALUES ('HICK01','Les Portes de la Mort','SF','Margaret Weis  et  Tracy Hickman');
INSERT INTO LIVRE VALUES ('LACK01','La proie de la magie','SF','Mercedes Lackey');
INSERT INTO LIVRE VALUES ('JOSS01','Voyages virtuels ','SF','Djimgee (alias Jean-Marc Josset');
INSERT INTO LIVRE VALUES ('BUJO01','La Proph�tie des pierres','SF','Flavia Bujor');
INSERT INTO LIVRE VALUES ('KOON01','La Maison interdite','SF','Dean R. Koontz');
INSERT INTO LIVRE VALUES ('WERB04','Les Fourmis','SF','Bernard Werber');
INSERT INTO LIVRE VALUES ('KING04','La Peau sur les Os','SF','Richard Bachman (Stephen King');
INSERT INTO LIVRE VALUES ('COLE01','N�philim, Le chant de la terre','SF','Isabelle et David Colet');
INSERT INTO LIVRE VALUES ('BORD01','Les guerriers du silence','SF','Pierre Bordage');
INSERT INTO LIVRE VALUES ('EDDI01','La Belgariade, suivi de La Mallor�e','SF','David Eddings');
INSERT INTO LIVRE VALUES ('LUML01','Necroscope','SF','Brian Lumley');
INSERT INTO LIVRE VALUES ('MAST01','D�mences','SF','Graham Masterton');
INSERT INTO LIVRE VALUES ('BARJ06','La nuit des temps','SF','Ren� Barjavel');
INSERT INTO LIVRE VALUES ('KEYE01','Des fleurs pour Algernon','SF','Daniel Keyes');
INSERT INTO LIVRE VALUES ('WILL01','Sans parler du chien','SF','Connie Willis');
INSERT INTO LIVRE VALUES ('GABO01','Les Cr�pusculaires','SF','Mathieu Gaborit');
INSERT INTO LIVRE VALUES ('DONA01','L''appel de Mordant','SF','Stephen Donaldson');
INSERT INTO LIVRE VALUES ('SIMM01','L''Echiquier du mal','SF','Dan Simmons');
INSERT INTO LIVRE VALUES ('LAWH01','Le cycle de Pendragon','SF','Stephen Lawhead');
INSERT INTO LIVRE VALUES ('PULL02','A la Crois�e des Mondes ','SF','Philip  Pullman');
INSERT INTO LIVRE VALUES ('CAUV01','Haute-Pierre','SF','Patrick Cauvin');
INSERT INTO LIVRE VALUES ('SIMM02','Le cycle d''Hyp�rion','SF','Dan Simmons');
INSERT INTO LIVRE VALUES ('HOBB02','Le prince Assassin','SF','Robin Hobb');
INSERT INTO LIVRE VALUES ('WERB06','L''ultime secret','SF','Bernard Werber');
INSERT INTO LIVRE VALUES ('PRER01','L''examen de rattrapage ','SF','Guillaume Prerrie');
INSERT INTO LIVRE VALUES ('SPIN01','Bleue comme une orange','SF','Norman Spinrad');
INSERT INTO LIVRE VALUES ('HOBB03','Les aventuriers de la mer','SF','Robin Hobb');
INSERT INTO LIVRE VALUES ('DICK01','Ubik','SF','Philip K. Dick');
INSERT INTO LIVRE VALUES ('BARJ07','La nuit des temps','SF','Ren� Barjavel');
INSERT INTO LIVRE VALUES ('RICE02','Lestat le Vampire','SF','Anne Rice');
INSERT INTO LIVRE VALUES ('KING05','Simeti�re','SF','Stephen KING');
INSERT INTO LIVRE VALUES ('HERB02','Dune','SF','Frank Herbert');
INSERT INTO LIVRE VALUES ('CARD01','La Strat�gie Ender','SF','Orson Scott Card');
INSERT INTO LIVRE VALUES ('BRUS05','Le syndrome du scaphandrier','SF','Serge Brussolo');
INSERT INTO LIVRE VALUES ('KOON02','Midnight','SF','Dean R. Koontz');
INSERT INTO LIVRE VALUES ('KING07','Dreamcatcher','SF','Stephen King');
INSERT INTO LIVRE VALUES ('ARNA02','La Compagnie des glaces','SF','Georges-Jean Arnaud');
INSERT INTO LIVRE VALUES ('MARQ01','Col�re','SF','Denis Marquet');
INSERT INTO LIVRE VALUES ('ANDE01','La maison des Atr��des','SF','Brian Herbert et Kevin J. Anderson');
INSERT INTO LIVRE VALUES ('MOKA02','La marque du diable','SF','Moka');
INSERT INTO LIVRE VALUES ('WERB08','L''ultime secret','SF','Bernard Werber');
INSERT INTO LIVRE VALUES ('BRUS06','Le manoir des sortil�ges','SF','Serge Brussolo');
INSERT INTO LIVRE VALUES ('WERB09','L''ultime secret','SF','Bernard Werber');
INSERT INTO LIVRE VALUES ('TOLK02','Le Silmarillion','SF','John Ronald Reuel Tolkien');
INSERT INTO LIVRE VALUES ('GUIL01','Les chemins du destin','SF','Franck Guilbert');
INSERT INTO LIVRE VALUES ('BARK01','Galil�e','SF','Clive Barker');
INSERT INTO LIVRE VALUES ('BARJ10','Ravage','SF','Ren� Barjavel');
INSERT INTO LIVRE VALUES ('WIND01','Blanche Neige, rouge sang','SF','Ellen Datlow et Terry Windling');
INSERT INTO LIVRE VALUES ('WERB13','L''ultime secret','SF','Bernard Werber');
INSERT INTO LIVRE VALUES ('WERB14','Les Fourmis','SF','Bernard Werber');
INSERT INTO LIVRE VALUES ('FETJ01','Le pas de Merlin','SF','Jean-Louis Fetjaine');
INSERT INTO LIVRE VALUES ('COLF02','Artemis Fowl','SF','Eoin Colfer');
INSERT INTO LIVRE VALUES ('PRAT04','La huiti�me couleur','SF','Terry Pratchett');
INSERT INTO LIVRE VALUES ('DICK02','Au bout du labyrinthe','SF','Philip K. Dick');
INSERT INTO LIVRE VALUES ('HOBB07','L''assassin royale','SF','Robin Hobb');
INSERT INTO LIVRE VALUES ('MOOR07','Voici l''homme','SF','Michael Moorcock');
INSERT INTO LIVRE VALUES ('LOEV01','La louve et l''enfant','SF','Henri Loevenbruck');
INSERT INTO LIVRE VALUES ('WILL02','Le 5e r�gne ','SF','Maxime Williams');
INSERT INTO LIVRE VALUES ('JORD02','La roue du temps','SF','Robert Jordan');
INSERT INTO LIVRE VALUES ('WURT01','La Trilogie de l''Empire','SF','Raymond E. Feist et Janny Wurts');
INSERT INTO LIVRE VALUES ('HOBB08','L''Assassin royal','SF','Robin Hobb');
INSERT INTO LIVRE VALUES ('LOEV02','La louve et l''enfant','SF','Henri Loevenbruck');
INSERT INTO LIVRE VALUES ('WERB15','Les Fourmis ','SF','Bernard Werber');
INSERT INTO LIVRE VALUES ('GEMM05','L�gende','SF','David Gemmell');
INSERT INTO LIVRE VALUES ('GAIM02','De bons pr�sages','SF','Terry Pratchett et Neil Gaiman');
INSERT INTO LIVRE VALUES ('KING09','Marche ou cr�ve','SF','Stephen King');
INSERT INTO LIVRE VALUES ('VARL01','Mill�nium','SF','John Varley');
INSERT INTO LIVRE VALUES ('ZELA01','Les Neuf Princes d''Ambre','SF','Roger Zelazny');
INSERT INTO LIVRE VALUES ('HOBB09','Les Aventuriers de la mer ','SF','Robin Hobb');
INSERT INTO LIVRE VALUES ('VINC02','Gauguin en Polyn�sie','Divers','Emanuelle Baum et Sarah Vincent');
INSERT INTO LIVRE VALUES ('SELL01','Atlas des peuples d''Orient : Moyen-Orient, Caucase, Asie centrale','Divers','Jean Sellier et Andr� Sellier');
INSERT INTO LIVRE VALUES ('GAUG01','Noa Noa','Divers','Paul Gauguin');
INSERT INTO LIVRE VALUES ('REDF02','La proph�tie des Andes','Divers','James Redfield');
INSERT INTO LIVRE VALUES ('MOUR05','Le go�t de Palerme','Divers','Jean-Noël Mouret');
INSERT INTO LIVRE VALUES ('HERZ01','Annapurna premier huit mille','Divers','Maurice Herzog');
INSERT INTO LIVRE VALUES ('KAPU01','Eb�ne, Aventures africaines','Divers','Ryszard Kapuscinski');
INSERT INTO LIVRE VALUES ('BONN02','La longue route de Jacob ben Ezra','Divers','Jacques Bonnet');
INSERT INTO LIVRE VALUES ('COUR03','A la d�couverte de la Lune','Divers','G�raud des Courtils');
INSERT INTO LIVRE VALUES ('ROSA02','L''esp�rance autour du monde','Divers','Christian de Boisredon, Nicolas de Fougeroux et Lo�c de Rosanbo');
INSERT INTO LIVRE VALUES ('OLLI01','La Longue Marche : Le Vent des steppes','Divers','Bernard Ollivier');
INSERT INTO LIVRE VALUES ('CHAR02','Papillon','Divers','Henri Charri�re');
INSERT INTO LIVRE VALUES ('POTA01','Le Port de la Mer de Glace','Divers','Dominique Potard');
INSERT INTO LIVRE VALUES ('NEEL01','Journal de voyage','Divers','Alexandra David-Neel');
INSERT INTO LIVRE VALUES ('JANI01','Damien autour du Monde','Divers','G�rard Janichon');
INSERT INTO LIVRE VALUES ('ROCH02','L''esclave de Dieu','Divers','Roger Frison-Roche');
INSERT INTO LIVRE VALUES ('TREH01','Tahiti, l''Eden � l''�preuve de la photographie','Divers','Jean-Yves Tr�hin');
INSERT INTO LIVRE VALUES ('HACK01','A pas feutr�s sur les sentiers sauvages de Lorraine','Divers','David Hackel');
INSERT INTO LIVRE VALUES ('RESC01','Esprit Loft 2','Divers','J�r�me de Vries et C�dric Resche');
INSERT INTO LIVRE VALUES ('DIDI02','Olympia, Bruno Coquatrix','Divers','Jean-Michel Boris, Jean-Fran�ois Brieu et Eric Didi');
INSERT INTO LIVRE VALUES ('LAMA01','Carnets de voyage','Divers','Titouan Lamazou');
INSERT INTO LIVRE VALUES ('MATT01','H�tels : Petites histoires de grands h�tels','Divers','Francisca Matteoli');
INSERT INTO LIVRE VALUES ('HEBE01','Esth�tique domestique : Les arts m�nagers 1920-1970','Divers','Jean-Bernard Hebey');
INSERT INTO LIVRE VALUES ('BREM01','L''intelligence de la couleur','Divers','Elisabeth Br�mond');
INSERT INTO LIVRE VALUES ('BRIO01','Regards sur le cin�ma am�ricain','Divers','Patrick Brion');
INSERT INTO LIVRE VALUES ('PODG01','La Pieta','Divers','Gregor Podgorski');
INSERT INTO LIVRE VALUES ('GRAD01','L''Alsace, le pays et ses habitants','Divers','Charles Grad');
INSERT INTO LIVRE VALUES ('GEOG01','Peuples du monde','Divers','Collectif - National Geographic');
INSERT INTO LIVRE VALUES ('PHOT01','Chamb�ry, une ville, des regards','Divers','10 �crivains et une photographe');
INSERT INTO LIVRE VALUES ('PACC01','Kamtchaka, la terre des origines','Divers','Yves Paccalet');
INSERT INTO LIVRE VALUES ('JEAN01','Esprit Loft','Divers','C�dric Resche, J�r�me de Vries, William Jean');
INSERT INTO LIVRE VALUES ('LAFF01','Enfants d''ailleurs','Divers','Martine et Caroline Laffon');
INSERT INTO LIVRE VALUES ('BERT01','365 jours pour la terre','Divers','Yann Arthus-Bertrand');
INSERT INTO LIVRE VALUES ('ROBE01','Cardon (Dessins)','Divers','Jean Robert');
INSERT INTO LIVRE VALUES ('BURN01','Le r�gne animal','Divers','David Burnie');
INSERT INTO LIVRE VALUES ('FOUG01','La fabuleuse aventure des hommes et des animaux','Divers','Boris Cyrulnick, Karine Lou Matignon, Fr�d�ric Fougea');
INSERT INTO LIVRE VALUES ('BERT02','La terre vue du ciel','Divers','Yann Arthus-Bertrand');
INSERT INTO LIVRE VALUES ('ATTA01','La conf�rence des oiseaux','Divers','Farid-ud-Din Attar');
INSERT INTO LIVRE VALUES ('PLIS01','La Mer','Divers','Philipp Plisson');
INSERT INTO LIVRE VALUES ('BERT03','La Terre vue du ciel, 2e �dition ','Divers','Yann Arthus-Bertrand');
INSERT INTO LIVRE VALUES ('SAUT01','Diamants','Divers','Hubert Bari et Violaine Sautter');
INSERT INTO LIVRE VALUES ('BERT04','La Terre vue du ciel','Divers','Yann Arthus-Bertrand');
INSERT INTO LIVRE VALUES ('DERR01','La Promesse du seuil : Un voyage avec Marguerite Yourcenar','Divers','Christian Dumais-Lvowski, Saddri Derradji');
INSERT INTO LIVRE VALUES ('MATR01','Qui et O�? R�gions de France','Divers','Chrystel Manfredi-Matringe');
INSERT INTO LIVRE VALUES ('MAJA01','Vaches, je vous aime','Divers','Photo : Roberto Neumiller / Texte : Jean-Olivier Majastre');
INSERT INTO LIVRE VALUES ('VERL01','Balavoine','Divers','Gilles Verlant');
INSERT INTO LIVRE VALUES ('LECH01','Cuisines d''Espagne','Divers','Elisabeth Lecharme');
INSERT INTO LIVRE VALUES ('PHOT04','Tout ce que vous devez avoir go�t� au moins une fois dans votre vie','Divers','Eric Frechon (recettes), Sylvia Gabet, Herv� Amiard (photographies');
INSERT INTO LIVRE VALUES ('HERM02','Mes desserts pr�f�r�s','Divers','Dorie Greespan et Pierre Herm');
INSERT INTO LIVRE VALUES ('LAUR01','La cuisine des Indiens : 50 recettes faciles au bon go�t d''aventure','Divers','Gilles et Laurence Laurendon');
INSERT INTO LIVRE VALUES ('COLL07','La cuisine asiatique pour tous','Divers','Collectif');
INSERT INTO LIVRE VALUES ('PELT01','Les �pices','Divers','Jean-Marie Pelt');
INSERT INTO LIVRE VALUES ('MART04','Le petit livre des cr�pes sal�es et sucr�es','Divers','H�lo�se Martel');
INSERT INTO LIVRE VALUES ('MOLI01','Verres gourmands','Divers','Beno�t Molin');
INSERT INTO LIVRE VALUES ('MATH01','La p�tisserie pour tous','Divers','Ginette Mathiot');
INSERT INTO LIVRE VALUES ('PHOT05','Je veux du chocolat !','Divers','Trish Deseine et Marie-Pierre Morel (photographe');
INSERT INTO LIVRE VALUES ('HERM03','Le Larousse des desserts','Divers','Pierre Herm');
INSERT INTO LIVRE VALUES ('CZAR01','Fromages du monde','Divers','Roland Barth�l�my et Arnaud Sperat-Czar');
INSERT INTO LIVRE VALUES ('ROBE02','Grand livre de la cuisine desserts et patisserie','Divers','Alain Ducasse et Fr�d�ric Robert');
INSERT INTO LIVRE VALUES ('ROBI01','L''Atlas mondial du vin','Divers','Hugh Johnson et Jancis Robinson');
INSERT INTO LIVRE VALUES ('LARO01','Petit Larousse de la cuisine 1800 recettes','Divers','Larousse');
INSERT INTO LIVRE VALUES ('CHEF01','Cuisiner pour les enfants','Divers','Marabout Chef');
INSERT INTO LIVRE VALUES ('LOIS01','Encyclop�die de la cuisine de A � Z (10 volumes)','Divers','France Loisirs');
INSERT INTO LIVRE VALUES ('COLL08','Basic Cooking - Cuisine asiatique entre copains','Divers','Collectif');
INSERT INTO LIVRE VALUES ('FLAM01','300 recettes des cuisines du monde','Divers','Collectif (Editions Flammarion');
INSERT INTO LIVRE VALUES ('DICK03','Basic cooking Cuisinez entre copains','Divers','Sabine S�lzer - Sebastian Dickhaut');
INSERT INTO LIVRE VALUES ('DUDE01','Les Cakes de Sophie','Divers','Sophie Dudemaine');
INSERT INTO LIVRE VALUES ('MATH02','La cuisine pour tous','Divers','Ginette Mathiot');
INSERT INTO LIVRE VALUES ('KAPL01','La nutrition consciente','Divers','Marion Kaplan');
INSERT INTO LIVRE VALUES ('GATT01','Un cours sur l''amour','Divers','Joan Gattuso');
INSERT INTO LIVRE VALUES ('ALBE01','Vie publique Vie priv�e','Divers','Francesco Alberoni');
INSERT INTO LIVRE VALUES ('SHIV01','Vaincre le stress par le yoga','Divers','Swami Shivapremananda');
INSERT INTO LIVRE VALUES ('FRAI01','Les hommes etc...','Divers','Ir�ne Frain');
INSERT INTO LIVRE VALUES ('DOLT01','Tout est language','Divers','Fran�oise Dolto');
INSERT INTO LIVRE VALUES ('GOUP01','Le Guide des amis en BD','Divers','Tepaz-Goupil');
INSERT INTO LIVRE VALUES ('JOHN01','Qui a piqu� mon fromage ?','Divers','Spencer Johnson');
INSERT INTO LIVRE VALUES ('MARI02','Plus de Platon moins de Prozac','Divers','Lou Marinoff');
INSERT INTO LIVRE VALUES ('SVEC01','Propri�taires, locataires, les r�gles du jeu','Divers','Val�rie Svec');

INSERT INTO LIVRE VALUES ('GLOC01','La vie en rose','Divers','Dominique glocheux');



-- PRET(COTE,LECTEUR,PRET,LIMITE,RENDU)
-- INSERT INTO PRET VALUES ('',,'','','');

INSERT INTO PRET VALUES('JOHN01',2,TO_DATE('02-04-01','DD-MM-YY'),TO_DATE('02-05-01','DD-MM-YY'),'non');

INSERT INTO PRET VALUES('KOUR01',2,TO_DATE('02-04-01','DD-MM-YY'),TO_DATE('02-06-01','DD-MM-YY'),'non');

INSERT INTO PRET VALUES('JONQ01',4,TO_DATE('19-03-03','DD-MM-YY'),TO_DATE('19-07-03','DD-MM-YY'),'oui');
INSERT INTO PRET VALUES('XIAO01',4,TO_DATE('25-09-02','DD-MM-YY'),TO_DATE('25-12-02','DD-MM-YY'),'oui');
INSERT INTO PRET VALUES('NOTT01',4,TO_DATE('13-04-01','DD-MM-YY'),TO_DATE('13-09-01','DD-MM-YY'),'oui');

INSERT INTO PRET VALUES('JONQ01',5,TO_DATE('19-03-03','DD-MM-YY'),TO_DATE('19-07-03','DD-MM-YY'),'oui');
INSERT INTO PRET VALUES('XIAO01',5,TO_DATE('25-09-02','DD-MM-YY'),TO_DATE('25-12-02','DD-MM-YY'),'non');
INSERT INTO PRET VALUES('NOTT01',5,TO_DATE('13-04-01','DD-MM-YY'),TO_DATE('13-09-01','DD-MM-YY'),'oui');

INSERT INTO PRET VALUES('JONQ01',9,TO_DATE('19-03-03','DD-MM-YY'),TO_DATE('19-07-03','DD-MM-YY'),'oui');
INSERT INTO PRET VALUES('XIAO01',9,TO_DATE('06-01-04','DD-MM-YY'),TO_DATE('16-02-04','DD-MM-YY'),'oui');
INSERT INTO PRET VALUES('NOTT01',9,TO_DATE('13-04-01','DD-MM-YY'),TO_DATE('13-09-01','DD-MM-YY'),'oui');

INSERT INTO  PRET VALUES ('CHAT01',11,TO_DATE('15-05-03','DD-MM-YY'),TO_DATE('15-06-03','DD-MM-YY'),'non');
INSERT INTO  PRET VALUES ('CHAT02',11,TO_DATE('15-05-03','DD-MM-YY'),TO_DATE('15-06-03','DD-MM-YY'),'oui');
INSERT INTO  PRET VALUES ('CHAT03',11,TO_DATE('15-05-03','DD-MM-YY'),TO_DATE('15-06-03','DD-MM-YY'),'oui');
INSERT INTO  PRET VALUES ('CHAT01',12,TO_DATE('27-09-03','DD-MM-YY'),TO_DATE('27-11-03','DD-MM-YY'),'oui');
INSERT INTO  PRET VALUES ('CHAT02',12,TO_DATE('27-09-03','DD-MM-YY'),TO_DATE('27-11-03','DD-MM-YY'),'oui');
INSERT INTO  PRET VALUES ('CHAT03',12,TO_DATE('27-09-03','DD-MM-YY'),TO_DATE('27-11-03','DD-MM-YY'),'oui');

INSERT INTO PRET VALUES('PERR01',2,TO_DATE('12-01-03','DD-MM-YY'),TO_DATE('12-03-03','DD-MM-YY'),'oui');
INSERT INTO PRET VALUES('PERR02',2,TO_DATE('25-02-03','DD-MM-YY'),TO_DATE('25-04-03','DD-MM-YY'),'oui');

INSERT INTO PRET VALUES('PERR03',2,TO_DATE('25-04-03','DD-MM-YY'),TO_DATE('25-07-03','DD-MM-YY'),'oui');
INSERT INTO PRET VALUES('LARO01',5,TO_DATE('12-12-2001','DD-MM-YYYY'),TO_DATE('12-02-2002','DD-MM-YYYY'),'non');
INSERT INTO PRET VALUES('JONQ01',14,TO_DATE('19-03-03','DD-MM-YY'),TO_DATE('19-07-03','DD-MM-YY'),'oui');

